---
- debug:
    msg: "Check to see if EULA variables are accepted"
  failed_when: (end_user_license_aggreement_consent_server != "Y" )or (end_user_license_aggreement_consent_cli != "YES")

- name: Import the MSFT gpg key
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add the MsSQL server repo
  yum_repository:
    name: mssql
    description: Microsoft SQL repo
    file: /etc/yum.repos.d/mssql-server.repo
    baseurl: https://packages.microsoft.com/config/rhel/8/mssql-server-2022.repo
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Add MsSQL command line tools repo
  yum_repository:
    name: mssql-cli-tools
    description: MsSQL ommand line prod tools repo
    file: /etc/yum.repos.d/msprod.repo
    baseurl: https://packages.microsoft.com/config/rhel/8/prod.repo
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Update all packages
  yum:
    name: '*'
    state: latest
