---

- debug:
    msg: "Check to see if EULA variables are accepted"
  failed_when: (end_user_license_aggreement_consent_server != "Y" )or (end_user_license_aggreement_consent_cli != "YES")

- name: Check if EPEL repository is already installed
  shell: rpm -q epel-release
  register: epel_installed
  ignore_errors: yes

- name: Install EPEL repository public key
  become: yes
  command: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  when: epel_installed.rc != 0
  tags:
    - epel

- name: Install EPEL repository
  when: epel_installed.rc != 0
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  tags:
    - epel

- name: Microsoft SQL Repository
  become: yes
  command: curl -o /etc/yum.repos.d/mssql-server.repo https://packages.microsoft.com/config/rhel/8/mssql-server-2022.repo

- name: Update package cache
  yum:
    update_cache: yes

- name: Install Microsoft SQL Server
  yum:
    name: "{{ mssql_packages }}"
    state: present

- name: Microsoft SQL Repository
  become: yes
  command: sudo curl -o /etc/yum.repos.d/msprod.repo https://packages.microsoft.com/config/rhel/8/prod.repo

- name: Remove older unixODBC files if performing upgrade
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ unixODBC_packages }}"

- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install mssql-cli-tool via command with args
  shell: ACCEPT_EULA=Y yum install mssql-tools -y
  when: install_cli

- name: Add mssql tools to .bashrc
  lineinfile:
    dest: "{{ bashrc_file }}"
    state: present
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
  when: install_cli

- name: Stop any existing mssql-server
  service:
    name: mssql-server
    state: stopped

- name: Run mssql setup script
  shell:  MSSQL_PID="{{edition}}" MSSQL_SA_PASSWORD="{{db_password}}" /opt/mssql/bin/mssql-conf -n setup accept-eula
  become_user: root
  register: setup_output
  failed_when: "'Setup has completed successfully. SQL Server is now starting.' not in setup_output.stdout"

- name: Stop any existing mssql-server
  service:
    name: mssql-server
    state: started
    enabled: yes
