---

unixODBC_packages:
  - unixODBC-utf16
  - unixODBC-utf16-devel

mssql_packages:
  - mssql-server
  - python-pip
  - python-devel

end_user_license_aggreement_consent_server: Y # Must be Y or N

end_user_license_aggreement_consent_cli: "YES" # Must be YES or NO in all caps within quotes

edition: Developer

db_name: testDB

db_host: 127.0.0.1

db_port: 1433

db_user: ec2-user

db_password: rootroot

import_file: /Users/kylebenson/Documents/Work/Vagrant/centos/Load_DB.sql

import_file_dest: /tmp/Load_DB.sql

enable_iptables: true

install_cli: true

