---

- debug:
    msg: "Check to see if EULA variables are accepted"
  failed_when: (end_user_license_aggreement_consent_server != "Y" )or (end_user_license_aggreement_consent_cli != "YES")

- name: Install dependencies
  apt: 
    name: "{{ dependencies }}"

- name: Download the Microsoft SQL Server signing key
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

- name: install mssql-server repo (Ubuntu)
  get_url:
    url: "{{ mssql_repo_url_ubuntu }}"
    dest: /etc/apt/sources.list.d/mssql-server.list

- name: Update package cache
  apt: update_cache=yes

- name: Install pymssql for future playbooks against DB server
  pip:
    name: pymssql
    state: present

- name: Install SQL Server
  apt:
    name: mssql-server
    state: present

- name: Start SQL Server
  service:
    name: mssql-server
    state: stopped

- name: Configure Microsoft SQL Server
  shell:  MSSQL_PID="{{edition}}" MSSQL_SA_PASSWORD="{{db_password}}" /opt/mssql/bin/mssql-conf -n setup accept-eula
  become: yes

- name: Start SQL Server
  service: 
    name: mssql-server 
    state: started 
    enabled: yes

- name: install mssql-tools repo (Ubuntu)
  get_url:
    url: "{{ mssql_tool_url_ubuntu }}"
    dest: /etc/apt/sources.list.d/mssql-tools.list

- name: refresh apt-get cache for tools repo (Ubuntu)
  command: apt-get update

- name: install mssql-tools package
  package:
    name: mssql-tools
    state: latest
  environment:
    ACCEPT_EULA: 'y'

- name: Add mssql tools to .bashrc
  lineinfile:
    dest: "{{ ansible_user_dir}}/.bashrc"
    state: present
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
  when: install_cli
